"""Fifth state

Revision ID: 3aba5eb5463b
Revises: 6cb2cac80a85
Create Date: 2020-12-15 18:15:00.562897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3aba5eb5463b'
down_revision = '6cb2cac80a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password_hash', sa.String(length=64), nullable=True))
    op.drop_column('User', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('User', 'password_hash')
    # ### end Alembic commands ###
