"""Fours state

Revision ID: 6cb2cac80a85
Revises: 7fbf4664bf91
Create Date: 2020-12-15 15:23:15.378434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb2cac80a85'
down_revision = '7fbf4664bf91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('picture', sa.String(length=30), nullable=True),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('actors', sa.String(length=200), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('firstname', sa.String(length=35), nullable=False),
    sa.Column('lastname', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=True),
    sa.Column('photo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('MovieSchedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=25), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['Movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=25), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['Movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reservation')
    op.drop_table('MovieSchedule')
    op.drop_table('User')
    op.drop_table('Movie')
    # ### end Alembic commands ###
