"""Nineth state

Revision ID: b48506e01ecf
Revises: ee2e7f94fd7a
Create Date: 2020-12-15 18:40:51.120497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48506e01ecf'
down_revision = 'ee2e7f94fd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
