"""Sixth state

Revision ID: bceb695ac7ec
Revises: 3aba5eb5463b
Create Date: 2020-12-15 18:17:41.378881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bceb695ac7ec'
down_revision = '3aba5eb5463b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
