"""Eights state

Revision ID: ee2e7f94fd7a
Revises: 596ac61c7bd1
Create Date: 2020-12-15 18:31:32.877776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2e7f94fd7a'
down_revision = '596ac61c7bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
